# Generated by Django 4.2.15 on 2024-08-26 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название секции')),
                ('number', models.IntegerField(default=1, verbose_name='Количество этажей')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название квартиры')),
                ('number', models.IntegerField(default=1, verbose_name='Номер квартиры в секции')),
                ('type', models.TextField(max_length=10, verbose_name='Тип квартиры')),
                ('small_square', models.FloatField(default=1, verbose_name='Площадь без летних')),
                ('shortened_square', models.FloatField(blank=True, default=1, null=True, verbose_name='Площадь с понижающими коэф.')),
                ('full_square', models.FloatField(blank=True, default=1, null=True, verbose_name='Площадь с летними')),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
    ]
