# Generated by Django 4.2.15 on 2024-08-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_alter_apartment_name_alter_section_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='name',
        ),
    ]
