# Generated by Django 4.2.15 on 2024-08-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_remove_apartment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='Section',
            new_name='section',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='type',
            field=models.TextField(choices=[('s', 'Студии'), ('1kk', '1-комнатные'), ('2kk', '2-комнатные'), ('3kk', '3-комнатные')], default='1kk', max_length=10, verbose_name='Тип квартиры'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.TextField(default='Секция ', max_length=100, verbose_name='Название секции'),
        ),
    ]
